# Generated by Django 5.2.1 on 2025-05-30 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_courseuser_gitlab_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggering_test_name', models.CharField(max_length=200)),
                ('triggering_status', models.BooleanField(default=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='courses.achievement')),
            ],
        ),
        migrations.CreateModel(
            name='CourseUserTriggerProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fulfilled', models.BooleanField(default=False)),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.achievementtrigger')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courseuser')),
            ],
        ),
    ]
