# Generated by Django 5.2.1 on 2025-05-30 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_achievementtrigger_courseusertriggerprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseusertriggerprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievement_progress', to='courses.courseuser'),
        ),
    ]
