# Generated by Django 5.2.1 on 2025-05-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_courseusertriggerprogress_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='courseusertriggerprogress',
            constraint=models.UniqueConstraint(fields=('user', 'trigger'), name='unique_user_trigger_progress'),
        ),
    ]
