# Generated by Django 5.2.1 on 2025-05-30 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_courseusertriggerprogress_unique_user_trigger_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseuser',
            name='achievements',
            field=models.ManyToManyField(blank=True, to='courses.achievement'),
        ),
    ]
